apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: magic-wallpapers
  name: magic-wallpapers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
