apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: magic-caddy-conf
  name: magic-caddy-conf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
